name: flutter_folio
description: Create and share beautiful Scrapbooks using Photos, Text and Stickers!
publish_to: "none"
version: 1.2.3

environment:
  sdk: '>=3.1.0 <4.0.0'    # this is for Dart

dependencies:
  flutter:
    sdk: flutter

  anchored_popups: ^0.1.0
  animate_do: ^3.1.2
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.0+1
  cached_network_image: ^3.0.0
  cloudinary_public: ^0.21.0
  context_menus: ^1.0.2
  darq: ^2.0.0
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0-nullsafety.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.0-nullsafety.1
  flutter_lorem: ^2.0.0
  flextras: ^1.0.0
  file_selector: ^1.0.1
  file_selector_windows: ^0.9.3+1
  file_selector_macos: ^0.9.3+3
  file_selector_linux: ^0.9.2+1
  file_selector_web: ^0.9.2+1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  image_size_getter: ^2.1.2
  multi_image_picker: ^4.8.00
  path_provider: ^2.0.1
  provider: ^6.1.1
  random_color: ^1.0.6-nullsafety
  sized_context: ^1.0.0+1
  shared_preferences: ^2.0.4
  share: ^2.0.1
  system_info: ^1.0.0
  statsfl: ^2.0.1+1
  timeago: ^3.0.2
  universal_platform: ^1.0.0-nullsafety
  url_launcher: ^6.0.2
  uuid: ^4.2.1
  visibility_detector: ^0.4.0+2

  # FIREBASE
  firedart: ^0.9.0+1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1

dev_dependencies:
  # sample build cmd
  # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable:
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.6

msix_config:
  display_name: Flutter Folio
  publisher_display_name: gskinner, inc
  identity_name: 56347gskinner-xboxapps.FlutterFolio
  msix_version: 1.2.3.0
  logo_path: ./source-assets/app-flutter-folio.png
  publisher: CN=8BC7C029-E8A6-4A58-BB90-CCCBD93A99FD
  capabilities: runFullTrust

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app-flutter-folio.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/emoji/
    - assets/images/logos/
    - assets/images/landing_page/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_72pt-SemiBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/scraps/AlfaSlabOne-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/scraps/Amiri-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/scraps/Caveat-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/scraps/Lato-Regular.ttf
    - family: Mali
      fonts:
        - asset: assets/fonts/scraps/Mali-Medium.ttf
    - family: PathwayGothicOne
      fonts:
        - asset: assets/fonts/scraps/PathwayGothicOne-Regular.ttf
